version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
        - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  pgadmin:
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: "abc@abc.com"
            PGADMIN_DEFAULT_PASSWORD: "123"
        ports: 
            - "4000:80"
        depends_on: 
            - postgres    
    